In [4]:
import pandas as pd

In [34]:
AS = pd.read_csv('pose_coordinates_combined.csv')
AS.head(3)
print(AS[['LeftHand']].head(100))

               LeftHand
0   (0.67, 0.54, -0.34)
1   (0.67, 0.54, -0.37)
2   (0.67, 0.54, -0.43)
3   (0.67, 0.54, -0.44)
4   (0.67, 0.53, -0.41)
5    (0.67, 0.53, -0.4)
6   (0.67, 0.53, -0.41)
7   (0.67, 0.53, -0.36)
8   (0.67, 0.53, -0.41)
9    (0.67, 0.53, -0.5)
10  (0.67, 0.53, -0.46)
11  (0.67, 0.53, -0.45)
12  (0.67, 0.53, -0.42)
13   (0.67, 0.53, -0.4)
14  (0.67, 0.53, -0.33)
15  (0.67, 0.53, -0.32)
16  (0.67, 0.53, -0.31)
17  (0.67, 0.53, -0.29)
18  (0.67, 0.53, -0.27)
19  (0.67, 0.53, -0.26)
20  (0.67, 0.53, -0.26)
21  (0.67, 0.53, -0.28)
22  (0.67, 0.53, -0.29)
23  (0.67, 0.53, -0.29)
24  (0.67, 0.53, -0.29)
25  (0.67, 0.53, -0.29)
26   (0.67, 0.53, -0.3)
27  (0.67, 0.53, -0.32)
28  (0.67, 0.53, -0.33)
29  (0.67, 0.53, -0.33)
30  (0.67, 0.53, -0.28)
31  (0.67, 0.53, -0.26)
32  (0.67, 0.53, -0.25)
33  (0.67, 0.53, -0.26)
34  (0.67, 0.53, -0.25)
35  (0.67, 0.53, -0.18)
36  (0.67, 0.53, -0.16)
37  (0.67, 0.53, -0.11)
38  (0.67, 0.53, -0.15)
39  (0.67, 0.53, -0.27)
40  (0.67, 0.53, -0.29)
41  (0.67, 0.53, -0.16)
42  (0.67, 0.53, -0.25)
43  (0.67, 0.53, -0.24)
44   (0.67, 0.53, -0.2)
45  (0.67, 0.53, -0.17)
46  (0.67, 0.53, -0.14)
47  (0.67, 0.53, -0.16)
48  (0.67, 0.53, -0.29)
49   (0.67, 0.53, -0.4)

In [22]:
import numpy as np

def calculate_angle(a, b, c):
    a = np.array(a)  # 첫 번째 점
    b = np.array(b)  # 중간 점 (관절)
    c = np.array(c)  # 세 번째 점
    
    # 각 축에 대한 벡터 계산
    ba = a - b  # b에서 a로의 벡터
    bc = c - b  # b에서 c로의 벡터

    # 각 축에 대한 각도 계산
    angle_x = np.arctan2(np.linalg.norm(np.cross(ba[[1,2]], bc[[1,2]])), np.dot(ba[[1,2]], bc[[1,2]]))
    angle_y = np.arctan2(np.linalg.norm(np.cross(ba[[0,2]], bc[[0,2]])), np.dot(ba[[0,2]], bc[[0,2]]))
    angle_z = np.arctan2(np.linalg.norm(np.cross(ba[[0,1]], bc[[0,1]])), np.dot(ba[[0,1]], bc[[0,1]]))

    # 라디안을 도(degree)로 변환
    angle_x = np.abs(angle_x*180.0/np.pi)
    angle_y = np.abs(angle_y*180.0/np.pi)
    angle_z = np.abs(angle_z*180.0/np.pi)

    angle_x = angle_x + 360 if angle_x < 0 else angle_x
    angle_y = angle_y + 360 if angle_y < 0 else angle_y
    angle_z = angle_z + 360 if angle_z < 0 else angle_z

    # 결과 반환
    return (round(angle_x, 4), round(angle_y, 4), round(angle_z, 4))  # 각 축에 대해 소수점 네 자리까지 반올림

In [26]:
aa = AS[['RightLeg', 'RightUpLeg', 'Hips']]
aa.head(11)

,RightLeg,RightUpLeg,Hips
0,"(0.4468, 0.6955, 0.0308)","(0.452, 0.5564, 0.0126)","(0.5113, 0.5546, -0.0)"
1,"(0.4465, 0.695, 0.0302)","(0.4523, 0.5586, 0.0126)","(0.5118, 0.5568, 0.0)"
2,"(0.4464, 0.695, 0.0412)","(0.4526, 0.5607, 0.0121)","(0.5122, 0.5587, -0.0001)"
3,"(0.4463, 0.6947, 0.0458)","(0.453, 0.5618, 0.0112)","(0.5126, 0.5599, -0.0)"
4,"(0.4461, 0.6947, 0.0995)","(0.4531, 0.562, 0.0118)","(0.5126, 0.5602, -0.0001)"
5,"(0.4461, 0.6949, 0.1244)","(0.4533, 0.5626, 0.012)","(0.5128, 0.5612, -0.0001)"
6,"(0.4464, 0.6945, 0.1339)","(0.4534, 0.5631, 0.0123)","(0.5128, 0.5619, -0.0001)"
7,"(0.4466, 0.6914, 0.115)","(0.4534, 0.5631, 0.0125)","(0.5128, 0.5619, -0.0001)"
8,"(0.4466, 0.6876, 0.0369)","(0.4534, 0.5632, 0.0104)","(0.5128, 0.562, -0.0001)"
9,"(0.447, 0.6852, -0.037)","(0.4536, 0.5634, 0.0096)","(0.513, 0.5623, -0.0001)"
10,"(0.4475, 0.6847, 0.0057)","(0.4537, 0.5636, 0.0096)","(0.5132, 0.5625, -0.0001)"

In [24]:
aa = AS[['RightLeg', 'RightUpLeg', 'Hips']]
alist = []

for i in range(len(aa)):
    # Convert tuple strings to actual tuples if necessary
    a = eval(aa['RightLeg'][i]) if isinstance(aa['RightLeg'][i], str) else aa['RightLeg'][i]
    b = eval(aa['RightUpLeg'][i]) if isinstance(aa['RightUpLeg'][i], str) else aa['RightUpLeg'][i]
    c = eval(aa['Hips'][i]) if isinstance(aa['Hips'][i], str) else aa['Hips'][i]

    angle = calculate_angle(a, b, c)
    alist.append(angle)

alist

[(105.5844, 117.9411, 93.8795),
 (105.4825, 120.196, 94.1677),
 (111.5357, 113.596, 94.5652),
 (114.2209, 111.6021, 94.712),
 (132.0617, 105.8735, 94.7524),
 (136.9506, 105.1602, 94.463),
 (138.3093, 105.086, 94.2067),
 (134.062, 105.7717, 94.1912),
 (108.5453, 114.4163, 94.2861),
 (75.5332, 88.7867, 94.1626),
 (94.6253, 138.5696, 93.99),
 (117.1173, 107.0326, 93.7466),
 (127.8695, 106.1996, 93.8926),
 (135.8631, 106.9214, 94.1009),
 (138.0628, 107.3702, 94.361),
 (132.6235, 108.0412, 94.3588),
 (132.9075, 108.2669, 94.4173),
 (127.7457, 109.1333, 94.4349),
 (121.0318, 110.5956, 94.5588),
 (113.4788, 113.0333, 94.4784),
 (102.9541, 126.6702, 94.449),
 (93.319, 122.9209, 94.4699),
 (96.3512, 159.4169, 94.4729),
 (101.2707, 137.4931, 94.417),
 (100.4766, 140.5374, 94.2662),
 (98.2394, 167.6094, 94.2636),
 (102.0751, 131.3058, 94.3064),
 (122.422, 106.5019, 94.334),
 (129.4896, 105.2685, 94.5191),
 (134.5949, 105.1087, 94.6778),
 (134.7149, 104.3702, 94.7344),
 (129.5802, 104.9809, 94.8041),
 (123.4533, 106.7844, 95.0324),
 (125.197, 105.9457, 95.1671),
 (127.0934, 105.0568, 95.1213),
 (120.0239, 107.545, 95.0206),
 (120.6127, 106.8916, 94.9226),
 (118.4939, 106.9547, 94.6287),
 (51.7036, 87.1302, 93.3345),
 (67.8992, 94.5462, 92.3226),
 (62.1322, 93.5235, 91.7131),
 (89.5777, 112.1745, 91.5107),
 (90.6644, 109.4362, 91.6444),
 (91.4982, 107.2285, 91.6951),
 (74.7168, 99.0912, 91.692),
 (83.0637, 96.1356, 91.8848),
 (81.2299, 96.13, 92.2337),
 (94.1487, 97.9268, 92.358),
 (110.4925, 99.6393, 92.2772),
 (97.4417, 109.4025, 92.3875),
 (89.5913, 134.2306, 92.4422),
 (68.5218, 92.4252, 92.1697),
 (63.3148, 89.9536, 91.7601),
 (54.4549, 88.374, 91.1639),
 (51.7997, 88.9732, 90.759),
 (58.5504, 91.1072, 90.7085),
 (76.1542, 151.4208, 90.5758),
 (79.1659, 109.8891, 90.4398),
 (75.4461, 108.89, 90.6004),
 (76.0129, 107.5639, 90.5606),
 (89.2589, 99.2791, 90.6117),
 (87.4405, 101.0233, 90.7093),
 (87.2351, 102.1511, 90.8068),
 (82.2966, 107.7026, 90.9378),
 (84.0504, 106.9449, 91.1237),
 (92.788, 101.287, 91.2621),
 (98.4476, 99.1155, 91.3583),
 (96.8039, 99.5481, 91.414),
 (98.1901, 99.51, 91.4735),
 (97.759, 100.0042, 91.3854),
 (87.6528, 106.7046, 91.4318),
 (87.1607, 106.9083, 91.439),
 (87.4428, 107.3085, 91.5766),
 (82.7925, 121.9596, 91.7273),
 (84.6999, 121.8505, 91.9671),
 (102.5391, 100.2056, 92.0667),
 (111.552, 97.9301, 92.057),
 (120.7076, 96.5993, 92.0285),
 (118.9487, 97.2337, 92.1115),
 (117.8116, 97.3689, 92.0936),
 (117.8507, 97.2943, 92.0418),
 (116.5917, 97.387, 91.9094),
 (114.9504, 97.5764, 91.6809),
 (122.233, 96.658, 91.4322),
 (126.3163, 96.3379, 91.4336),
 (125.134, 96.0395, 91.3893),
 (124.7435, 96.0703, 91.3845),
 (124.8534, 96.2816, 91.3009),
 (125.3175, 96.2333, 91.3163),
 (124.7537, 96.3303, 91.3556),
 (124.3756, 96.5008, 91.3975),
 (124.6472, 96.621, 91.3496),
 (128.7346, 96.5191, 91.2032),
 (131.9097, 96.4884, 91.3018),
 (132.7278, 96.483, 91.3425),
 (127.7336, 96.8923, 91.3487),
 (123.0356, 97.3597, 91.4391),
 (118.423, 97.7762, 91.4864),
 (118.8605, 97.6352, 91.4886),
 (118.8258, 97.4741, 91.4335),
 (125.3399, 96.8897, 91.4307),
 (127.1109, 96.5869, 91.4734),
 (125.4346, 96.4555, 91.4146),
 (120.0052, 96.5546, 91.3997),
 (117.388, 96.544, 91.2114),
 (116.5922, 95.8331, 91.0831),
 (123.184, 95.0804, 90.8299),
 (131.689, 95.672, 90.2409),
 (135.3316, 96.6888, 89.9316),
 (135.3046, 96.7486, 89.7633),
 (132.7341, 96.7736, 89.7215),
 (118.9155, 95.7381, 89.727),
 (85.0538, 98.6762, 89.6839),
 (77.6815, 110.2245, 89.7757),
 (70.9561, 167.3404, 89.8135),
 (88.7377, 97.4574, 89.9913),
 (98.3286, 96.9248, 90.4561),
 (98.1692, 98.2324, 90.8198),
 (72.1541, 98.9266, 91.092),
 (23.8322, 96.929, 91.2371),
 (49.808, 92.6016, 91.4102),
 (127.996, 93.9518, 91.4277),
 (136.7864, 94.4896, 91.4479),
 (137.3239, 94.6087, 91.5086),
 (137.3346, 93.8359, 91.5159),
 (126.6692, 92.9467, 91.4678),
 (138.664, 93.2398, 91.9088),
 (120.3462, 94.9392, 91.9127),
 (117.548, 94.6539, 91.9169),
 (119.6384, 94.4509, 91.9749),
 (108.4133, 95.1183, 91.9739),
 (116.3753, 95.2665, 92.2244),
 (121.9807, 95.4557, 92.2828),
 (129.2891, 94.5622, 92.0795),
 (128.7811, 94.5433, 91.6547),
 (130.9591, 96.3898, 91.5025),
 (129.0072, 96.9094, 91.595),
 (120.0719, 95.828, 91.3989),
 (23.9668, 93.8838, 91.3382),
 (57.6161, 90.1919, 91.6053),
 (57.2993, 90.8701, 91.7877),
 (44.4152, 90.2756, 91.7625),
 (35.6305, 91.1518, 91.6461),
 (19.8216, 91.9808, 91.6805),
 (17.3978, 92.1318, 91.7126),
 (16.8988, 92.1267, 91.7521),
 (19.0263, 91.9933, 91.6306),
 (74.574, 94.1634, 91.3077),
 (98.9568, 96.1737, 90.9528),
 (94.2009, 98.5653, 90.9506),
 (93.5068, 97.8537, 90.7105),
 (78.3907, 98.7547, 90.8638)]

In [7]:
AS = pd.read_csv('pose_angle_combined.csv')
AS.head(10)

,Spine,LeftUpLeg,RightUpLeg,Spine2,Neck,RightArm,RightShoulder,LeftArm,LeftShoulder,RightLeg,LeftLeg
0,"(0.0, 0.0, 0.0)","(69.3241, 94.817, 92.388)","(105.5844, 117.9411, 93.8795)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(83.943, 17.0238, 151.8101)","(159.2176, 114.1939, 118.5574)","(104.3238, 3.864, 137.7638)","(17.2605, 105.068, 124.3881)","(113.458, 162.95, 174.0131)","(121.4126, 164.1536, 179.157)"
1,"(0.0, 0.0, 0.0)","(87.4975, 136.4651, 92.1428)","(105.4825, 120.196, 94.1677)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(75.669, 22.1075, 150.8209)","(150.3722, 121.3225, 119.2284)","(94.244, 9.2565, 137.9399)","(21.6692, 104.5199, 123.8302)","(112.4043, 160.4394, 172.6633)","(100.6576, 35.5418, 179.6573)"
2,"(0.0, 0.0, 0.0)","(88.876, 125.5244, 91.7852)","(111.5357, 113.596, 94.5652)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(79.4056, 25.8661, 149.6506)","(146.9778, 124.9754, 120.1548)","(83.8866, 19.617, 138.1676)","(26.6766, 109.3247, 123.3834)","(116.7959, 166.5639, 171.9524)","(97.6756, 25.0699, 179.8664)"
3,"(0.0, 0.0, 0.0)","(76.9492, 126.3678, 91.9462)","(114.2209, 111.6021, 94.712)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(84.0609, 30.183, 148.5723)","(146.488, 127.639, 120.9894)","(86.3138, 24.302, 138.4314)","(28.0721, 115.2994, 123.0632)","(119.1196, 167.6154, 171.6288)","(108.7271, 133.8077, 179.6348)"
4,"(0.0, 0.0, 0.0)","(53.005, 85.4114, 92.0185)","(132.0617, 105.8735, 94.7524)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(88.8783, 37.3655, 148.7476)","(137.1092, 135.8905, 121.3414)","(91.45, 19.9498, 138.1739)","(27.6249, 111.6133, 123.2816)","(138.0662, 173.9413, 171.2605)","(134.2691, 174.3525, 179.8858)"
5,"(0.0, 0.0, 0.0)","(41.6122, 82.2625, 92.1629)","(136.9506, 105.1602, 94.463)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(80.3801, 31.0918, 148.7481)","(148.2767, 127.1354, 121.7029)","(88.8277, 12.7182, 138.2287)","(16.2738, 107.9498, 123.3567)","(144.1876, 174.8972, 171.0672)","(147.1797, 177.2247, 179.7344)"
6,"(0.0, 0.0, 0.0)","(39.1065, 81.4782, 92.2353)","(138.3093, 105.086, 94.2067)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(78.066, 28.6443, 148.4412)","(150.2325, 125.4444, 122.2437)","(87.6771, 12.1032, 137.4948)","(17.9285, 106.6711, 123.9303)","(146.7877, 175.1958, 170.9196)","(150.6086, 177.6815, 179.6261)"
7,"(0.0, 0.0, 0.0)","(60.8694, 85.1032, 91.9549)","(134.062, 105.7717, 94.1912)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(81.431, 29.6905, 147.5166)","(149.8617, 126.4011, 123.1228)","(94.482, 3.1468, 136.3808)","(13.8114, 104.3528, 124.7852)","(143.3469, 174.6401, 171.0334)","(128.9314, 174.0382, 179.0863)"
8,"(0.0, 0.0, 0.0)","(106.8, 106.6405, 91.7142)","(108.5453, 114.4163, 94.2861)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(82.4229, 34.3014, 147.7076)","(147.902, 129.4722, 123.3986)","(80.7102, 19.0418, 136.4826)","(17.6466, 111.4748, 125.1301)","(118.1186, 163.9235, 171.0503)","(83.6139, 7.8921, 178.7389)"
9,"(0.0, 0.0, 0.0)","(125.2892, 102.0927, 91.5611)","(75.5332, 88.7867, 94.1626)","(0.0, 0.0, 0.0)","(0.0, 0.0, 0.0)","(81.0304, 35.7992, 147.6482)","(142.3097, 133.2241, 123.8557)","(76.2155, 32.4771, 136.9471)","(34.1979, 118.9311, 125.2738)","(85.9676, 6.3711, 171.3526)","(65.517, 4.2593, 178.3622)"

In [19]:
joints = [
    "Hips","Spine","Spine1","Spine2",
    "LeftShoulder","LeftArm","LeftForeArm","LeftHand",
    "LeftHandIndex1","LeftHandIndex2","LeftHandIndex3","LeftHandMiddle1",
    "LeftHandMiddle2","LeftHandMiddle3","LeftHandPinky1","LeftHandPinky2",
    "LeftHandPinky3","LeftHandRing1","LeftHandRing2",
    "LeftHandRing3","LeftHandThumb1","LeftHandThumb2",
    "LeftHandThumb3","Neck","Head","RightShoulder","RightArm",
    "RightForeArm","RightHand","RightHandIndex1",
    "RightHandIndex2","RightHandIndex3","RightHandMiddle1",
    "RightHandMiddle2","RightHandMiddle3","RightHandPinky1",
    "RightHandPinky2","RightHandPinky3","RightHandRing1",
    "RightHandRing2","RightHandRing3","RightHandThumb1",
    "RightHandThumb2","RightHandThumb3","LeftUpLeg","LeftLeg",
    "LeftFoot","LeftToeBase","RightUpLeg","RightLeg","RightFoot",
    "RightToeBase"
]
len(joints)

52

In [17]:
a = "0.0000 94.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 -270.0000 90.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0001 0.0000 0.0000 0.0000 0.0000 -0.0013 -0.0008 0.0000 -0.0004 0.0001 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0003 0.0000 0.0000 -0.0007 0.0003 0.0000 0.0004 -0.0006 0.0000 0.0000 0.0001 0.0000 0.0000 0.0000 0.0000 -0.0010 -0.0002 0.0000 0.0002 30.0001 -0.0001 0.0005 -29.9998 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 270.0001 90.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 -0.0001 0.0001 0.0000 0.0000 0.0000 0.0000 -0.0006 0.0003 0.0000 -0.0001 0.0001 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0007 0.0001 0.0000 -0.0011 0.0001 0.0000 -0.0008 0.0003 0.0000 0.0001 0.0000 0.0000 0.0000 0.0000 0.0000 -0.0009 0.0000 0.0000 0.0002 -29.9997 -0.0001 -0.0002 29.9996 0.0000 0.0000 0.0000 0.0000 0.0000 180.0000 0.0000 0.0001 0.0826 -0.1744 64.6492 -0.1930 0.0000 25.3510 0.0000 0.0000 0.0000 180.0000 0.0000 0.0000 -0.0827 0.1745 64.6492 0.1931 0.0000 25.3508 -0.0001"
b = a.split()
c=len(b)
c

159

In [18]:
a = '0.5129 0.6144 -0.0 0.0000 0.0000 0.0000 0.0000 0.0000 81.8911 0.0000 0.0000 0.0000 0.0000 0.0000 98.1089 0.0000 0.0000 86.1784 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 48.5167 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 112.8461 0.0000 0.0000 0.0000 0.0000 0.0000 112.9631 0.0000 0.0000 18.074 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 95.3543 0.0000 0.0000 160.0673 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 92.1064 0.0000 0.0000 167.8391 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000'
b = a.split()
c=len(b)
c

159